image: node:20

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  PRODUCTION_DOMAIN: 13.212.6.189
  DEPLOY_USER: ubuntu
  DEPLOY_HOST: 13.212.6.189
  DEPLOY_PATH: /var/www/testing  
  SSH_EC2_PRIVATE_KEY: $SSH_EC2_PRIVATE_KEY 
  DIST_DEPLOY_PATH : /home/ubuntu/frontend/dist/

build:
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm run build
    - ls -la ./dist
  artifacts:
    paths:
      - ./dist
  only:
    - develop

deploy:
  stage: deploy production
  environment:
    name: production
    url: https://$PRODUCTION_DOMAIN
  before_script:
    - apt-get update -y && apt-get install -y openssh-client rsync   
    - eval $(ssh-agent -s)  
    - echo "$SSH_EC2_PRIVATE_KEY" | tr -d '\r' > private_key.pem 
    - chmod 400 private_key.pem  
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts 

  script:
    - echo "Deploying to EC2 staging..."
    - rsync -avz -e "ssh -i private_key.pem" ./dist/ ubuntu@$DEPLOY_HOST:$DIST_DEPLOY_PATH
    - ssh -i "private_key.pem" ubuntu@$DEPLOY_HOST"
      echo 'Deployment complete!' &&
      ls -l $DIST_DEPLOY_PATH &&
      sudo nginx -t &&
      sudo systemctl restart nginx &&
      "
  only: 
    - develop