version: '3'
services:
  client:
    image: 'git.clp.kr:5050/anbschool/2nd/hexcode/team-projects/wavetrack-guest/landing:latest'
    container_name: landing
    restart: always
    ports:
      - '5174:5174'
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
