version: '3'
services:
  landing:
    image: 'git.clp.kr:5050/anbschool/2nd/hexcode/team-projects/wavetrack-guest/landing:latest'
    container_name: landing
    restart: always
    ports:
      - '5174:80'
    networks:
      - shared-network
    environment:
      # EmailJS Key
      VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
      VITE_EMAILJS_TEMPLATE_ID: ${VITE_EMAILJS_SERVICE_ID}
      VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_SERVICE_ID}

networks:
  shared-network:
    driver: bridge
