# Specify the base image for the build stage
FROM node:20 AS build

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies (use caching for faster builds)
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the application
RUN npm run build

# Serve the application with NGINX
FROM nginx:alpine

# Copy built files from the previous stage
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

# Expose the port that your application will run on
EXPOSE 5173

