# Stage 1: Build the React application
FROM node:20 AS build

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies (use caching for faster builds)
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the React application
RUN npm run build

# Stage 2: Serve the application with NGINX
FROM nginx:alpine

# Copy built files from the previous stage to the nginx html folder
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

# Set the right permissions 
RUN chmod -R 755 /usr/share/nginx/html

# Expose port 5174 since Nginx serves HTTP on this port
EXPOSE 5174

# Start NGINX server
CMD ["nginx", "-g", "daemon off;"]
